//Problem 1: FizzBuzz = Find all the multiples of 3 and 5 below 1000 and add them together. 



// Problem 2 
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.


// Find the sum of the even valued terms of the F sequence 
//xn = xn− 1 + xn− 2
//The next number is found by adding up the number before it 


xn =


    a = math.pow(x)